### ISSUE TITLE
Crash when clicking on "Verify" button

### ISSUE THREAD

**Issue by spipau** [konstantintutsch/Lock#15]
### Describe the bug …

1. Open Lock
2. Change to "File"
3. Click Button "Verify" (Question Mark Button)
4. Crash

Ubuntu 24.04.1 LTS, GNOME 46, Wayland

Also, non of the other functions work…

### Which version of Lock are you using?

1.0.0+2

### Source

Flathub

### Relevant log output

```shell
flatpak run com.konstantintutsch.Lock 
** Message: 14:16:11.105: GnuPG Made Easy 1.23.2
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers

(com.konstantintutsch.Lock:2): GLib-GIO-CRITICAL **: 14:16:16.125: g_file_get_path: assertion 'G_IS_FILE (file)' failed

(com.konstantintutsch.Lock:2): GLib-GIO-CRITICAL **: 14:16:16.125: g_file_get_path: assertion 'G_IS_FILE (file)' failed

** (com.konstantintutsch.Lock:2): WARNING **: 14:16:16.204: Fehler beim Erstellen von GPGME Eingangsdaten aus einer Datei: Ungültiger Wert
```

**Comment by konstantintutsch** [comment]
Jup, that's the error

**Comment by konstantintutsch** [comment]
Seems like I forgot to implement that when implementing threading

**Comment by sstendahl** [comment]
> Seems like I forgot to implement that when implementing threading

Great, good to see you're on it :)

Interesting timing with this initial issue by the way. I installed this days ago (think this tool was featured on TWIG), noticed this just about now and wanted to file an issue. Only to find that this was reported like 3 minutes before I wanted to file the issue :P
