### ISSUE TITLE
Can't compile with `-Werror=format-security`

### ISSUE THREAD

**Issue by getchoo** [konstantintutsch/Lock#26]
### Describe the bug …

```
 ../src/cryptography.c: In function 'key_manage':
 ../src/cryptography.c:234:9: error: format not a string literal and no format arguments [-Werror=format-security]
   234 |         fprintf(file, armor);
       |
```

This may be a source of [potential UB](https://en.wikipedia.org/wiki/Uncontrolled_format_string) when exporting the key -- though this unlikely

### Which version of Lock are you using?

1.1.2

### Source

Build locally

### Relevant log output

```shell
n/a
```

**Comment by konstantintutsch** [comment]
Thank you for reporting!

The fix is available in [`v1.1.3`](https://github.com/konstantintutsch/Lock/releases/tag/v1.1.3) :)
