### ISSUE TITLE
Remove split sentences in translations

### ISSUE THREAD

**Issue by yakushabb** [konstantintutsch/Lock#29]
### Describe the bug …

There are several split sentences, which usually make translating the strings difficult

https://github.com/konstantintutsch/Lock/blob/main/src/cryptography.c#L16

More information: https://wiki.gnome.org/TranslationProject(2f)DevGuidelines(2f)Never(20)split(20)sentences.html

### Relevant log output

```shell
#define HANDLE_ERROR(Return, Error, String, Context, FreeCode) if (Error) \
    { \
        g_warning(C_("Error message constructor for failed GPGME operations", "Failed to %s: %s"), String, gpgme_strerror(Error)); \
        \
        FreeCode \
        \
        gpgme_release(Context); \
        \
        return Return; \
    }
```

**Comment by konstantintutsch** [comment]
The new strings should now also be available in the Turkish translation.

Just checked and Weblate did not apply the changes from fe9101e91d6e32dd41569253dc95e1aaeb2b92dc to the Turkish translation for some reason. It's fixed.
