### ISSUE TITLE
`--socket=gpg-agent` causes unexpected Pinentry behavior

### ISSUE THREAD

**Issue by konstantintutsch** [konstantintutsch/Lock#32]
I've identified that the issues are caused by having the `'gpg-agent'` socket enabled in the sandbox.

https://github.com/user-attachments/assets/43c3196d-448f-4f03-8f13-db9f79738934

_Originally posted by @TellThatToLuke in https://github.com/konstantintutsch/Lock/issues/30#issuecomment-2496133626_

**Comment by TellThatToLuke** [comment]
@konstantintutsch Thank you for addressing my issues promptly and for releasing such a useful app that moves away from performing these operations via the command line! :blush: :tada:
