### ISSUE TITLE
Fail signing

### ISSUE THREAD

**Issue by RZHSSNZDH** [konstantintutsch/Lock#39]
### Describe the bug …

According to https://github.com/konstantintutsch/Lock/issues/38#issuecomment-2504682585 I opened this issue. What could be the problem?

The keys which I do not have their secret keys are listed in sign list and when I choose them I get `Signing failed` error. It is normal to be failed signing, but it should not be listed in the dialog.

### Which version of Lock are you using?

1.2.2

### Which version of GnuPG Made Easy is Lock using?

1.23.2

### Which distribution did this bug occur on?

Arch

### Source

Flathub

### Console Output (stdout)

```shell
** Message: 18:08:43.888: GnuPG Made Easy 1.23.2
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:752: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan_hasvk/anv_formats.c:783: FINISHME: support more multi-planar formats with DRM modifiers

** (com.konstantintutsch.Lock:2): WARNING **: 18:08:51.385: Failed to sign GPGME data from memory: Unusable secret key
```

### ~/.gnupg/gpg.conf

```shell
I do not have this file!
```

### ~/.gnupg/gpg-agent.conf

```shell
I do not have this file too!
```

**Comment by konstantintutsch** [comment]
Seems like I unintentionally fixed this in 25eab873e93c04ab3aa22690c36d9089b1e2de90.

https://github.com/konstantintutsch/Lock/blob/25eab873e93c04ab3aa22690c36d9089b1e2de90/src/selectiondialog.c#L139-L143

Thank you for reporting!
